// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnx_dTWw-IHz5qPIB3JANu7c-6UHCEC8w',
    appId: '1:188979148272:web:18daee43997c5b4c44d935',
    messagingSenderId: '188979148272',
    projectId: 'testproject-45469',
    authDomain: 'testproject-45469.firebaseapp.com',
    databaseURL: 'https://testproject-45469-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-45469.appspot.com',
    measurementId: 'G-PYV9E35H6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6NuISyWt2qV3iNa7V71KoTpfYOgAAMJA',
    appId: '1:188979148272:android:b7f4adf613e24ebd44d935',
    messagingSenderId: '188979148272',
    projectId: 'testproject-45469',
    databaseURL: 'https://testproject-45469-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-45469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7UMY9w7o-Q-hHExCmkfVEKPaRSsaXXds',
    appId: '1:188979148272:ios:3955b51be6e44b4544d935',
    messagingSenderId: '188979148272',
    projectId: 'testproject-45469',
    databaseURL: 'https://testproject-45469-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-45469.appspot.com',
    iosBundleId: 'com.example.folksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7UMY9w7o-Q-hHExCmkfVEKPaRSsaXXds',
    appId: '1:188979148272:ios:3955b51be6e44b4544d935',
    messagingSenderId: '188979148272',
    projectId: 'testproject-45469',
    databaseURL: 'https://testproject-45469-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-45469.appspot.com',
    iosBundleId: 'com.example.folksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnx_dTWw-IHz5qPIB3JANu7c-6UHCEC8w',
    appId: '1:188979148272:web:9b943aa1711b288244d935',
    messagingSenderId: '188979148272',
    projectId: 'testproject-45469',
    authDomain: 'testproject-45469.firebaseapp.com',
    databaseURL: 'https://testproject-45469-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-45469.appspot.com',
    measurementId: 'G-8RS8273VHR',
  );
}
