const List<String> cuisineOptions = [
  'Italian',
  'Chinese',
  'Indian',
  'Mexican',
  'Thai',
  'Japanese',
  'French',
  'Mediterranean',
  'American',
  'Lebanese',
  'Spanish',
  'Greek',
  'Turkish',
  'Korean',
  'Vietnamese',
  'Brazilian',
  'Moroccan',
  'Caribbean',
  'German',
  'Russian'
];

const List<String> tagOptions = [
  'Fish Allergic Free',
  'Prawn Allergic Free',
  'Pork Free',
  'Halal',
  'Vegetarian',
  'Vegan',
  'Gluten Free',
  'Nut Free',
  'Dairy Free',
  'Egg Free',
  'Soy Free',
  'Kosher',
  'Organic',
  'Locally Sourced',
  'Low Carb',
  'Low Sugar',
  'Keto Friendly',
  'High Protein',
  'Family Friendly',
  'Pet Friendly'
];
